export const emptyField = [
   [
      {x: 0, y: 0, isShip: false, marker: false},
      {x: 1, y: 0, isShip: false, marker: false},
      {x: 2, y: 0, isShip: false, marker: false},
      {x: 3, y: 0, isShip: false, marker: false},
      {x: 4, y: 0, isShip: false, marker: false},
      {x: 5, y: 0, isShip: false, marker: false},
      {x: 6, y: 0, isShip: false, marker: false},
      {x: 7, y: 0, isShip: false, marker: false},
      {x: 8, y: 0, isShip: false, marker: false},
      {x: 9, y: 0, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 1, isShip: false, marker: false},
      {x: 1, y: 1, isShip: false, marker: false},
      {x: 2, y: 1, isShip: false, marker: false},
      {x: 3, y: 1, isShip: false, marker: false},
      {x: 4, y: 1, isShip: false, marker: false},
      {x: 5, y: 1, isShip: false, marker: false},
      {x: 6, y: 1, isShip: false, marker: false},
      {x: 7, y: 1, isShip: false, marker: false},
      {x: 8, y: 1, isShip: false, marker: false},
      {x: 9, y: 1, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 2, isShip: false, marker: false},
      {x: 1, y: 2, isShip: false, marker: false},
      {x: 2, y: 2, isShip: false, marker: false},
      {x: 3, y: 2, isShip: false, marker: false},
      {x: 4, y: 2, isShip: false, marker: false},
      {x: 5, y: 2, isShip: false, marker: false},
      {x: 6, y: 2, isShip: false, marker: false},
      {x: 7, y: 2, isShip: false, marker: false},
      {x: 8, y: 2, isShip: false, marker: false},
      {x: 9, y: 2, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 3, isShip: false, marker: false},
      {x: 1, y: 3, isShip: false, marker: false},
      {x: 2, y: 3, isShip: false, marker: false},
      {x: 3, y: 3, isShip: false, marker: false},
      {x: 4, y: 3, isShip: false, marker: false},
      {x: 5, y: 3, isShip: false, marker: false},
      {x: 6, y: 3, isShip: false, marker: false},
      {x: 7, y: 3, isShip: false, marker: false},
      {x: 8, y: 3, isShip: false, marker: false},
      {x: 9, y: 3, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 4, isShip: false, marker: false},
      {x: 1, y: 4, isShip: false, marker: false},
      {x: 2, y: 4, isShip: false, marker: false},
      {x: 3, y: 4, isShip: false, marker: false},
      {x: 4, y: 4, isShip: false, marker: false},
      {x: 5, y: 4, isShip: false, marker: false},
      {x: 6, y: 4, isShip: false, marker: false},
      {x: 7, y: 4, isShip: false, marker: false},
      {x: 8, y: 4, isShip: false, marker: false},
      {x: 9, y: 4, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 5, isShip: false, marker: false},
      {x: 1, y: 5, isShip: false, marker: false},
      {x: 2, y: 5, isShip: false, marker: false},
      {x: 3, y: 5, isShip: false, marker: false},
      {x: 4, y: 5, isShip: false, marker: false},
      {x: 5, y: 5, isShip: false, marker: false},
      {x: 6, y: 5, isShip: false, marker: false},
      {x: 7, y: 5, isShip: false, marker: false},
      {x: 8, y: 5, isShip: false, marker: false},
      {x: 9, y: 5, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 6, isShip: false, marker: false},
      {x: 1, y: 6, isShip: false, marker: false},
      {x: 2, y: 6, isShip: false, marker: false},
      {x: 3, y: 6, isShip: false, marker: false},
      {x: 4, y: 6, isShip: false, marker: false},
      {x: 5, y: 6, isShip: false, marker: false},
      {x: 6, y: 6, isShip: false, marker: false},
      {x: 7, y: 6, isShip: false, marker: false},
      {x: 8, y: 6, isShip: false, marker: false},
      {x: 9, y: 6, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 7, isShip: false, marker: false},
      {x: 1, y: 7, isShip: false, marker: false},
      {x: 2, y: 7, isShip: false, marker: false},
      {x: 3, y: 7, isShip: false, marker: false},
      {x: 4, y: 7, isShip: false, marker: false},
      {x: 5, y: 7, isShip: false, marker: false},
      {x: 6, y: 7, isShip: false, marker: false},
      {x: 7, y: 7, isShip: false, marker: false},
      {x: 8, y: 7, isShip: false, marker: false},
      {x: 9, y: 7, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 8, isShip: false, marker: false},
      {x: 1, y: 8, isShip: false, marker: false},
      {x: 2, y: 8, isShip: false, marker: false},
      {x: 3, y: 8, isShip: false, marker: false},
      {x: 4, y: 8, isShip: false, marker: false},
      {x: 5, y: 8, isShip: false, marker: false},
      {x: 6, y: 8, isShip: false, marker: false},
      {x: 7, y: 8, isShip: false, marker: false},
      {x: 8, y: 8, isShip: false, marker: false},
      {x: 9, y: 8, isShip: false, marker: false},
   ],
   [
      {x: 0, y: 9, isShip: false, marker: false},
      {x: 1, y: 9, isShip: false, marker: false},
      {x: 2, y: 9, isShip: false, marker: false},
      {x: 3, y: 9, isShip: false, marker: false},
      {x: 4, y: 9, isShip: false, marker: false},
      {x: 5, y: 9, isShip: false, marker: false},
      {x: 6, y: 9, isShip: false, marker: false},
      {x: 7, y: 9, isShip: false, marker: false},
      {x: 8, y: 9, isShip: false, marker: false},
      {x: 9, y: 9, isShip: false, marker: false},
   ],
];
